CREATE TABLE "worker" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "worker_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"farm" text,
	"role" text,
	"status" integer DEFAULT 1 NOT NULL,
	"created_by" integer,
	"created_at" bigint DEFAULT extract(epoch from now())::bigint NOT NULL,
	"updated_by" integer,
	"updated_at" bigint DEFAULT extract(epoch from now())::bigint NOT NULL,
	CONSTRAINT "worker_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "crop_prediction" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "crop_prediction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"soil_data_id" integer,
	"crop" text NOT NULL,
	"state" text NOT NULL,
	"season" text NOT NULL,
	"area_hectares" double precision NOT NULL,
	"custom_question" text,
	"prediction" text,
	"yield_per_hectare" text,
	"total_yield" text,
	"profitability" text,
	"techniques" text,
	"raw_ai_response" text,
	"created_at" bigint DEFAULT extract(epoch from now())::bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "email" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "role" ALTER COLUMN "id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "worker" ADD CONSTRAINT "worker_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "worker" ADD CONSTRAINT "worker_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "worker" ADD CONSTRAINT "worker_updated_by_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "crop_prediction" ADD CONSTRAINT "crop_prediction_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "crop_prediction" ADD CONSTRAINT "crop_prediction_soil_data_id_soil_data_id_fk" FOREIGN KEY ("soil_data_id") REFERENCES "public"."soil_data"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "worker_user_id_idx" ON "worker" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "worker_status_idx" ON "worker" USING btree ("status");--> statement-breakpoint
CREATE INDEX "crop_prediction_user_id_idx" ON "crop_prediction" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "crop_prediction_created_at_idx" ON "crop_prediction" USING btree ("created_at");