import { EnumItem } from '@/lib/enum/enum-item.type';

export const STATES = {
  ANDAMAN_NICOBAR: new EnumItem(1, 'Andaman and Nicobar Islands'),
  ANDHRA_PRADESH: new EnumItem(2, 'Andhra Pradesh'),
  ARUNACHAL_PRADESH: new EnumItem(3, 'Arunachal Pradesh'),
  ASSAM: new EnumItem(4, 'Assam'),
  BIHAR: new EnumItem(5, 'Bihar'),
  CHANDIGARH: new EnumItem(6, 'Chandigarh'),
  CHHATTISGARH: new EnumItem(7, 'Chhattisgarh'),
  DADRA_NAGAR_HAVELI: new EnumItem(8, 'Dadra and Nagar Haveli'),
  DAMAN_DIU: new EnumItem(9, 'Daman and Diu'),
  DELHI: new EnumItem(10, 'Delhi'),
  GOA: new EnumItem(11, 'Goa'),
  GUJARAT: new EnumItem(12, 'Gujarat'),
  HARYANA: new EnumItem(13, 'Haryana'),
  HIMACHAL_PRADESH: new EnumItem(14, 'Himachal Pradesh'),
  JAMMU_KASHMIR: new EnumItem(15, 'Jammu and Kashmir'),
  JHARKHAND: new EnumItem(16, 'Jharkhand'),
  KARNATAKA: new EnumItem(17, 'Karnataka'),
  KERALA: new EnumItem(18, 'Kerala'),
  LADAKH: new EnumItem(19, 'Ladakh'),
  LAKSHADWEEP: new EnumItem(20, 'Lakshadweep'),
  MADHYA_PRADESH: new EnumItem(21, 'Madhya Pradesh'),
  MAHARASHTRA: new EnumItem(22, 'Maharashtra'),
  MANIPUR: new EnumItem(23, 'Manipur'),
  MEGHALAYA: new EnumItem(24, 'Meghalaya'),
  MIZORAM: new EnumItem(25, 'Mizoram'),
  NAGALAND: new EnumItem(26, 'Nagaland'),
  ODISHA: new EnumItem(27, 'Odisha'),
  PUDUCHERRY: new EnumItem(28, 'Puducherry'),
  PUNJAB: new EnumItem(29, 'Punjab'),
  RAJASTHAN: new EnumItem(30, 'Rajasthan'),
  SIKKIM: new EnumItem(31, 'Sikkim'),
  TAMIL_NADU: new EnumItem(32, 'Tamil Nadu'),
  TELANGANA: new EnumItem(33, 'Telangana'),
  TRIPURA: new EnumItem(34, 'Tripura'),
  UTTAR_PRADESH: new EnumItem(35, 'Uttar Pradesh'),
  UTTARAKHAND: new EnumItem(36, 'Uttarakhand'),
  WEST_BENGAL: new EnumItem(37, 'West Bengal'),
} as const;


